#include QMK_KEYBOARD_H
#include "features/caps_word.h"

bool process_record_user(uint16_t keycode, keyrecord_t* record) {
  if (!process_caps_word(keycode, record)) { return false; }
  // Your macros ...

  return true;
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_DEL, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_ENT, KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_BSPC, KC_SPC, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_TAB, KC_LGUI, MO(1), KC_BSPC, KC_SPC, MO(2), KC_RALT),
	[1] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TAB, KC_PERC, KC_AT, KC_LCBR, KC_RCBR, KC_AMPR, KC_EQL, KC_7, KC_8, KC_9, KC_PLUS, KC_DEL, KC_GRV, KC_QUOT, KC_DQUO, KC_LPRN, KC_RPRN, KC_EXLM, KC_MINS, KC_4, KC_5, KC_6, KC_HASH, KC_ASTR, KC_TILD, KC_BSLS, KC_PIPE, KC_LBRC, KC_RBRC, KC_CIRC, KC_BSPC, KC_SPC, KC_UNDS, KC_1, KC_2, KC_3, KC_DLR, KC_ESC, KC_TRNS, KC_NO, KC_BSPC, KC_SPC, KC_0, KC_TRNS),
	[2] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TAB, KC_EXLM, KC_VOLD, KC_MUTE, KC_VOLU, KC_INS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LSFT, KC_HOME, KC_END, KC_PGUP, KC_PGDN, KC_NUM, KC_TRNS, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_TRNS, KC_LCTL, LCTL(KC_Z), LCTL(KC_X), LCTL(KC_C), LCTL(KC_V), KC_LGUI, KC_BSPC, KC_SPC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LCTL(LSFT(KC_GRAVE)), LCTL(LSFT(KC_P)), KC_BSPC, KC_SPC, KC_NO, KC_TRNS)
};
